quarkus:
  banner:
    path: banner.txt

  swagger-ui:
    always-include: true
    path: ${quarkus.http.root-path}/docs

  analytics:
    disabled: true

  native:
    resources:
      includes:
        - GRAALPY-VFS//**

  graalpy:
    vfs-path: GRAALPY-VFS/dev.martindotpy/quarkus-and-python

# Development profile
"%dev":
  quarkus:
    log:
      console:
        format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n"

  mp:
    openapi:
      extensions:
        smallrye:
          property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategies$SnakeCaseStrategy
